### ISSUE TITLE
README fix about multiset rules

### ISSUE THREAD

**Issue by Smoren** [markrogoyski/itertools-php#25]
https://github.com/markrogoyski/itertools-php/blob/e13f5be9ae94ce042af5c122d70429d0027ff38e/README.md?plain=1#L961

Do we realy need this clarification?

Look at all the points:
1. If input iterables produce duplicate items, then [multiset](https://en.wikipedia.org/wiki/Multiset) intersection rules apply.
2. If `$minIntersectionCount` is 1, then [multiset](https://en.wikipedia.org/wiki/Multiset) union rules apply.

* So if we have multisets on input then we have the case (1).
* When we have `$minIntersectionCount = 1` and multisets on input, then we still have case (1).
* And when we have `$minIntersectionCount = 1` and common sets on input, then no multisets rules needed.

So i think the case (2) is redundant.

**Comment by Smoren** [comment]
Hi @markrogoyski,

Have you already seen this issue? I think this needs to be fixed before the next release.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Sure, if you think it is unnecessary. I went ahead and removed it.

**Comment by Smoren** [comment]
Thank you Mark!

**Comment by Smoren** [comment]
Thank you @markrogoyski,

I saw your commit, but this line is repeated several times for defferent methods in README. I think we need to remove them all.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thanks for the heads up. I removed another one. Let me know if I missed any other comments.

Thanks.

**Comment by Smoren** [comment]
Hi @markrogoyski,

Thank you, I think everything is OK now!
