### ISSUE TITLE
Pipe functionlity suggestion

### ISSUE THREAD

**Issue by Smoren** [markrogoyski/itertools-php#29]
Hi @markrogoyski,

What do you think about implementing pipe functionality in itertools? Something like this:

```php
class Pipe
{
    /**
     * @var array<callable>
     */
    protected array $funcs = [];

    /**
     * @param array<callable> $funcs
     */
    public function __construct(array $funcs)
    {
        $this->funcs = $funcs;
    }

    /**
     * @param mixed $x
     * @return mixed
     */
    public function __invoke($x)
    {
        return array_reduce($this->funcs, fn ($carry, $func) => $func($carry), $x);
    }
}

$pipe = new Pipe(
    fn ($x) => $x**2,
    fn ($x) => $x+1,
);

$result = $pipe(3);
// 10 (3^2 + 1)
```

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for proposing your idea. It seems like a sequential pipeline of operations, passing the result of one operation as the input to the next, similar to UNIX pipes on the command line. You could also think of it as a workflow.

It's an interesting idea and I'm curious what some more advanced use cases look like. However, my initial impression is that I'm not sure it is a good fit for IterTools. For example, while Streams are a pipeline of operations, they are operations on iterables that involve looping through all the elements at each step in the stream pipeline. In your example, there is an order of operations, but it does not involve looping/iteration.

It's an interesting idea. Maybe worth having as it's own project to develop the idea. I just don't think it naturally fits with the theme of Itertools.

Thanks,
Mark

**Comment by Smoren** [comment]
Hi @markrogoyski,

My idea was about using pipes with other methods of IterTools as a callable instance. Like this:

```php
$pipe = new Pipe(
    fn ($x) => $x**2,
    fn ($x) => $x+1,
);
$input = [1, 2, 3];
foreach (Single::map($input, $pipe)) {
    // 2, 5, 10
}
```

**Comment by markrogoyski** [comment]
Hi @Smoren,

I think you can do the same thing right now with `Stream` and maybe it is more intuitive, as it doesn't require additional classes and interfaces to accomplish it.

For example:
```php
$result = Stream::of([1, 2, 3])
    ->map(fn ($x) => $x**2)
    ->map(fn ($x) => $x + 1)
    ->toArray();
```

The nice thing about `Single::map` is that it is flexible and I think it would work with your proposed `Pipe` right now if it existed.

I think the Pipe/Workflow concept is good and can be paired with functionality like IterTools that accepts functions as arguments. It just doesn't seem like a natural fit for functionality to exist _in_ IterTools. IterTools already offers a lot of functionality, but it is all consistent with a theme of iteration and looping. Adding additional functionality, even if it is cool and useful, but not consistent with the theme of the project, can be confusing and an additional hurdle for people to use the library.

I would recommend developing the Pipe/SequentialWorkflow idea as a separate project, and not be constrained to only thinking how it works in the context of this library, but as a more universal pipe/workflow tool.

**Comment by Smoren** [comment]
So I'm closing this issue.

**Comment by Smoren** [comment]
So I'm closing this issue.
